config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :arifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end

  resources :members
  get 'home/index'

   root :to => "home#index"


  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match 'user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions",
    :passwords => "milia/passwords",
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan


end

app/models/arifact.rb
class Arifact < ActiveRecord::Base
  before_save :upload_to_s3
  attr_accessor :upload
  belongs_to :project

  MAX_FILESIZE = 10.megabytes
  validates_presence_of :name, :upload
  validates_uniqueness_of :name

  validate :uploaded_file_size

  private

  def uploaded_file_size
    if upload
      errors.add(:upload, "Max file size is #{self.class::MAX_FILESIZE}") unless upload.size <= self.class::MAX_FILESIZE
    end
  end

  def upload_to_s3
    s3 = Aws::S3::Resource.new
    tenant_name = Tenant.find(Thread.current[:tenant_id]).name
    obj = s3.bucket(ENV['S3_BUCKET']).object("#{tenant_name}/#{upload.original_filename}")
    obj.upload_file(upload.path, acl:'public-read')
    self.key = obj.public_url
  end
end

app/controllers/arifacts_controller.rb
class ArifactsController < ApplicationController
  before_action :set_arifact, only: [:show, :edit, :update, :destroy]

  # GET /arifacts
  # GET /arifacts.json
  def index
    @arifacts = Arifact.all
  end

  # GET /arifacts/1
  # GET /arifacts/1.json
  def show
  end

  # GET /arifacts/new
  def new
    @arifact = Arifact.new
    @arifact.project_id = params[:project_id]
  end

  # GET /arifacts/1/edit
  def edit
  end

  # POST /arifacts
  # POST /arifacts.json
  def create
    @arifact = Arifact.new(arifact_params)

    respond_to do |format|
      if @arifact.save
        format.html { redirect_to tenant_project_url(tenant_id: Tenant.current_tenant_id, id: @arifact.project.id), notice: 'Arifact was successfully created.' }
        format.json { render :show, status: :created, location: @arifact }
      else
        format.html { render :new }
        format.json { render json: @arifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arifacts/1
  # PATCH/PUT /arifacts/1.json
  def update
    respond_to do |format|
      if @arifact.update(arifact_params)
        format.html { redirect_to @arifact, notice: 'Arifact was successfully updated.' }
        format.json { render :show, status: :ok, location: @arifact }
      else
        format.html { render :edit }
        format.json { render json: @arifact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arifacts/1
  # DELETE /arifacts/1.json
  def destroy
    @arifact.destroy
    respond_to do |format|
      format.html { redirect_to tenant_project_url(tenant_id: Tenant.current_tenant_id, id: @arifact.project_id), notice: 'Arifact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arifact
      @arifact = Arifact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arifact_params
      params.require(:arifact).permit(:name, :project_id, :upload)
    end
end

app/helpers/arifacts_helper.rb
module ArifactsHelper
end

app/views/arifacts/_form.html.erb
<%= form_for @arifact, :html => { :class => "form-horizontal arifact" } do |f| %>

  <% if @arifact.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@arifact.errors.count, "error") %> prohibited this arifact from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @arifact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :upload, value: "File to upload", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :upload, :class => 'form-control' %>
    </div>
  </div>
  <%= f.hidden_field :project_id %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tenant_project_path(tenant_id: Tenant.current_tenant_id, id: @arifact.project.id), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/arifacts/_list.html.erb
<%- model_class = Arifact -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:key) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% arifacts.each do |arifact| %>
      <tr>
        <td><%= link_to arifact.name, arifact_path(arifact), class: 'main-link' %></td>
        <td><%= s3_link Tenant.current_tenant_id, arifact.key %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      arifact_path(arifact),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Artifafct', new_arifact_path(project_id: @project.id), :class => 'btn btn-primary' %>

app/views/arifacts/edit.html.erb
<%- model_class = Arifact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/arifacts/index.html.erb
<%= render 'arifacts/list', arifacts: @project.arifacts %>

app/views/arifacts/new.html.erb
<%- model_class = Arifact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/arifacts/show.html.erb
<%- model_class = Arifact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @arifact.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:key) %>:</strong></dt>
  <dd><%= @arifact.key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @arifact.project_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              arifacts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_arifact_path(@arifact), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              arifact_path(@arifact),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>